---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/checkinfo/beta.checkinfo.in
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rm -f $DEPLOYPATH/.htaccess
    - /bin/cp -R .next $DEPLOYPATH/
    - /bin/cp -R node_modules $DEPLOYPATH/
    - /bin/cp -R public $DEPLOYPATH/
    - /bin/cp package.json server.js app.cjs Passengerfile.json index.html $DEPLOYPATH/
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 0755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 0644 {} \;
